version: 2
build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv tool install --from maturin@latest maturin
    - uv sync --group docs --no-group dev --frozen --no-cache --python 3.12
    - uv run --no-sync maturin develop --uv --frozen
    - uv run --no-sync mkdocs build -d $READTHEDOCS_OUTPUT/html
